import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../Components/01. Navbar/Navbar";
import Main from "../Components/02. Index/01. Main/Main";
import Footer from "../Components/Footer/Footer";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Navbar />
      <Main />
      <Footer />
    </div>
  );
};

export default Home;
